-- Cute Weather - Supabase Schema
-- Run this in Supabase SQL Editor (https://app.supabase.com)
-- This creates the 'locations' table with the 'source' column
-- to track whether a location was added via GPS (realtime) or manual search.

create table if not exists locations (
  id bigint generated by default as identity primary key,
  name text,
  latitude double precision,
  longitude double precision,
  icon_type text default 'default',
  source text default 'manual', -- 'manual' (search/default) or 'realtime' (GPS)
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable Row Level Security (recommended for production)
alter table locations enable row level security;

-- Allow read access to all locations
create policy "Allow read access" on locations for select using (true);

-- Allow insert access
create policy "Allow insert access" on locations for insert with check (true);

-- Allow delete access (for admin cleanup)
create policy "Allow delete access" on locations for delete using (true);

-- Optional: Add comment for documentation
comment on column locations.source is 'Source of location: "manual" for search/default, "realtime" for GPS location button';
